# routers/chat.py

import time
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import JSONResponse

from agents.coordinator import run
from models.request_models import ChatRequest
from models.response_models import ChatResponse


# ── Router Initialization ─────────────────────────────────────────────────────
router = APIRouter(
    prefix="/chat",
    tags=["Chat"],
)


# ══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

def build_chat_response(
    coordinator_result: dict,
    query: str,
    processing_time_ms: float,
) -> dict:
    """
    Build the final structured response dict sent to the frontend.

    Merges the coordinator result with request metadata (original query,
    processing time) into one clean response object that matches the
    ChatResponse Pydantic model.

    Args:
        coordinator_result  : Full result dict from agents/coordinator.run()
        query               : Original user query string
        processing_time_ms  : Total pipeline execution time in milliseconds

    Returns:
        Dict matching the ChatResponse model structure.
    """
    return {
        "query":              query,
        "response":           coordinator_result.get("response", ""),
        "task_type":          coordinator_result.get("task_type", "UNKNOWN"),
        "sources":            coordinator_result.get("sources", []),
        "chunks_used":        coordinator_result.get("chunks_used", 0),
        "top_score":          coordinator_result.get("top_score", 0.0),
        "avg_score":          coordinator_result.get("avg_score", 0.0),
        "used_fallback":      coordinator_result.get("used_fallback", False),
        "is_valid":           coordinator_result.get("is_valid", True),
        "warnings":           coordinator_result.get("warnings", []),
        "error":              coordinator_result.get("error", None),
        "processing_time_ms": round(processing_time_ms, 2),
    }


# ══════════════════════════════════════════════════════════════════════════════
# ROUTE 1 — SEND CHAT MESSAGE
# POST /chat/query
# ══════════════════════════════════════════════════════════════════════════════

@router.post(
    "/query",
    response_model=ChatResponse,
    status_code=status.HTTP_200_OK,
)
async def chat_query(request: ChatRequest):
    """
    Main chat endpoint. Accepts a user query and returns a legal analysis
    response generated by the full multi-agent pipeline.

    The request body is validated by the ChatRequest Pydantic model before
    this function runs. If validation fails, FastAPI returns a 422 automatically.

    Pipeline:
        1. Record start time
        2. Pass query to Coordinator Agent (classify → retrieve → explain)
        3. Record end time and compute processing duration
        4. Build and return structured response

    Request body:
        {
            "query": "What are the GDPR penalties for data breaches?"
        }

    Response 200:
        {
            "query"              : "What are the GDPR penalties...",
            "response"           : "**Legal Analysis**\n\n...",
            "task_type"          : "RETRIEVAL",
            "sources"            : ["gdpr.pdf"],
            "chunks_used"        : 5,
            "top_score"          : 0.87,
            "avg_score"          : 0.74,
            "used_fallback"      : false,
            "is_valid"           : true,
            "warnings"           : [],
            "error"              : null,
            "processing_time_ms" : 2340.5
        }

    Response 422:
        Automatic FastAPI validation error if request body is malformed.

    Response 500:
        { "detail": "Unexpected server error: <message>" }
    """
    print(f"\n{'▶' * 60}")
    print(f"  POST /chat/query")
    print(f"  Query: {request.query[:100]}{'...' if len(request.query) > 100 else ''}")
    print(f"{'▶' * 60}")

    # ── Step 1 — Start Timer ──────────────────────────────────────────────────
    start_time = time.perf_counter()

    # ── Step 2 — Run Coordinator Pipeline ────────────────────────────────────
    try:
        coordinator_result = run(query=request.query)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Unexpected server error: {str(e)}",
        )

    # ── Step 3 — Compute Processing Time ─────────────────────────────────────
    end_time = time.perf_counter()
    processing_time_ms = (end_time - start_time) * 1000

    print(f"⏱️  Processing time: {processing_time_ms:.2f}ms")

    # ── Step 4 — Build and Return Response ───────────────────────────────────
    response_data = build_chat_response(
        coordinator_result=coordinator_result,
        query=request.query,
        processing_time_ms=processing_time_ms,
    )

    return JSONResponse(
        status_code=status.HTTP_200_OK,
        content=response_data,
    )


# ══════════════════════════════════════════════════════════════════════════════
# ROUTE 2 — HEALTH CHECK
# GET /chat/health
# ══════════════════════════════════════════════════════════════════════════════

@router.get("/health", status_code=status.HTTP_200_OK)
async def health_check():
    """
    Lightweight health check endpoint for the chat pipeline.

    Verifies that the Coordinator Agent and its dependencies are importable
    and the router is reachable. Does not make any LLM or ChromaDB calls —
    this keeps the health check fast and cost-free.

    Used by:
        - Frontend on app load to confirm backend is reachable
        - Deployment pipelines to confirm service is healthy after startup

    Response 200:
        {
            "status"  : "healthy",
            "service" : "chat",
            "message" : "Chat pipeline is ready to receive queries."
        }
    """
    return {
        "status":  "healthy",
        "service": "chat",
        "message": "Chat pipeline is ready to receive queries.",
    }


# ══════════════════════════════════════════════════════════════════════════════
# ROUTE 3 — PIPELINE TEST
# POST /chat/test
# ══════════════════════════════════════════════════════════════════════════════

@router.post("/test", status_code=status.HTTP_200_OK)
async def test_pipeline(request: ChatRequest):
    """
    Test endpoint that runs the full pipeline but returns extended
    diagnostic information not included in the standard /query response.

    Intended for development and debugging only. In production you would
    restrict this endpoint or remove it entirely.

    Includes everything from /query plus:
        - classification_label : The raw task type returned by the Coordinator
        - retrieval_score_info : Top and average retrieval scores
        - fallback_triggered   : Whether the no-results fallback was used
        - validation_passed    : Whether the response passed all checks
        - warning_count        : Number of validation warnings raised

    Request body:
        {
            "query": "What does habeas corpus mean?"
        }

    Response 200:
        Full ChatResponse fields plus diagnostic fields listed above.
    """
    print(f"\n🧪 POST /chat/test — Diagnostic run")

    start_time = time.perf_counter()

    try:
        coordinator_result = run(query=request.query)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Pipeline test failed: {str(e)}",
        )

    end_time = time.perf_counter()
    processing_time_ms = (end_time - start_time) * 1000

    base_response = build_chat_response(
        coordinator_result=coordinator_result,
        query=request.query,
        processing_time_ms=processing_time_ms,
    )

    # ── Append Diagnostic Fields ──────────────────────────────────────────────
    diagnostic_response = {
        **base_response,
        "classification_label": coordinator_result.get("task_type", "UNKNOWN"),
        "retrieval_score_info": {
            "top_score": coordinator_result.get("top_score", 0.0),
            "avg_score": coordinator_result.get("avg_score", 0.0),
            "chunks_used": coordinator_result.get("chunks_used", 0),
        },
        "fallback_triggered":  coordinator_result.get("used_fallback", False),
        "validation_passed":   coordinator_result.get("is_valid", True),
        "warning_count":       len(coordinator_result.get("warnings", [])),
    }

    return JSONResponse(
        status_code=status.HTTP_200_OK,
        content=diagnostic_response,
    )


# ══════════════════════════════════════════════════════════════════════════════
# ROUTE 4 — CLASSIFY ONLY (No Retrieval, No LLM Generation)
# POST /chat/classify
# ══════════════════════════════════════════════════════════════════════════════

@router.post("/classify", status_code=status.HTTP_200_OK)
async def classify_only(request: ChatRequest):
    """
    Classify a query without running the full pipeline.

    Calls only the Coordinator's classification step — no retrieval,
    no LLM generation beyond the routing call. Returns the task type
    label and the processing time for the classification alone.

    Useful for:
        - Frontend to show the user what type of task their query triggered
          before the full response arrives (e.g. a badge showing "RETRIEVAL")
        - Testing and validating the routing prompt in isolation
        - Debugging misclassification issues during development

    Request body:
        {
            "query": "Compare GDPR with Pakistan's PDPA"
        }

    Response 200:
        {
            "query"              : "Compare GDPR with Pakistan's PDPA",
            "task_type"          : "COMPARISON",
            "processing_time_ms" : 340.2
        }
    """
    from agents.coordinator import classify

    print(f"\n🏷️  POST /chat/classify — Classification only")

    start_time = time.perf_counter()

    try:
        task_type = classify(query=request.query)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Classification failed: {str(e)}",
        )

    end_time = time.perf_counter()
    processing_time_ms = (end_time - start_time) * 1000

    return {
        "query":              request.query,
        "task_type":          task_type,
        "processing_time_ms": round(processing_time_ms, 2),
    }